# Generated by Django 3.0 on 2021-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnieje',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date_of_start', models.DateTimeField()),
                ('max_players', models.IntegerField()),
            ],
        ),
    ]
