# Generated by Django 3.0 on 2021-01-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0003_auto_20210121_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnieje',
            name='date_of_start',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Mecze',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('first_player', models.CharField(max_length=50)),
                ('second_player', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnieje.Turnieje')),
            ],
        ),
    ]
