# Generated by Django 3.0 on 2021-01-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0004_auto_20210126_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mecze',
            new_name='Games',
        ),
        migrations.RenameModel(
            old_name='Turnieje',
            new_name='Tournaments',
        ),
    ]
