# Generated by Django 3.0 on 2021-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0005_auto_20210126_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='first_player_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='second_player_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='first_player',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='second_player',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
