# Generated by Django 3.0 on 2021-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0006_auto_20210126_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
