# Generated by Django 3.0 on 2021-01-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0007_games_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='round',
            field=models.IntegerField(null=True),
        ),
    ]
