# Generated by Django 3.0 on 2021-01-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0008_auto_20210127_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='nr',
            field=models.IntegerField(null=True),
        ),
    ]
