# Generated by Django 3.0 on 2021-01-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnieje', '0009_auto_20210127_0255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
